### ISSUE TITLE
about the return value of store:verify

### ISSUE THREAD

**Issue by catbro666** [fffonion/lua-resty-openssl#109]
It seems better to return `false` [here](https://github.com/fffonion/lua-resty-openssl/blob/master/lib/resty/openssl/x509/store.lua#L223) in order to distinguish verification failure and error. What do you think? @fffonion

**Comment by fffonion** [comment]
@catbro666 it makes sense, but asking user relying on the difference of false and nil is dangerous, as Lua `assert()` also doesn't distinguish the two. So I would incline to keep it as is.

**Comment by catbro666** [comment]
How about returning other values? Returning 1 and 0 in Lua land also seems a bit weird:). Anyway, the difference between verification failure and error is not so critical, keeping it as is is also acceptable for me.
