### ISSUE TITLE
It's better not bind `X509_STORE_set_flags` logic in `store:add(crl)`

### ISSUE THREAD

**Issue by catbro666** [fffonion/lua-resty-openssl#110]
Adding crl file into the store does not necessarily mean the crl must be checked. The flag should be set on needs.
https://github.com/fffonion/lua-resty-openssl/blob/master/lib/resty/openssl/x509/store.lua#L78-L80

**Comment by fffonion** [comment]
@catbro666 It will make more sense to let user to control the flag if we are working on a much low-level API (for example, a one-to-one wrapping of X509_STORE openssl api into Lua). But most of the functions in this library are designed to use by end user, in this case it's better to keep the API as simple as possible. Asking user had to call two API for CRL check but only one for trusted chain is inbalanced.

I do see the use case from mtls-auth plugin, but generally speaking, the case of "add a CRL but not use it verification" is far less common then "add a CRL and use it verification". So I would incline to keep it as is.

**Comment by catbro666** [comment]
@fffonion Agree with high-level API should be easy to use and good by default. Setting this flag by default does make sense, but at least we should leave the possibility for the end user to not set it. The flag is not so easy to be unset, so what could have been done with one store now has to be done with two stores. OpenSSL doesn't provide direct wrapping API for unsetting flags on X509_STORE_CTX level, but does have `X509_VERIFY_PARAM_clear_flags`.  Maybe we can extend `store:verify` with a clear_flags parameter to support this.

**Comment by catbro666** [comment]
I got a more compelling reason now. There may be several independent CAs in the store and each CA has its own CRL. If we add the crl of ca1 into the store, and the api automatically set the flag to the store. Then when we verify the client cert issued by ca2, it will fail with ["unable to get certificate CRL"](https://github.com/openssl/openssl/blob/8c63b14296f117b07781509ced529a8955d78fb9/crypto/x509/x509_vfy.c#L1022)

**Comment by fffonion** [comment]
In that case you shoudn't be adding the CRL of ca1 in the first place: only add what you intend to be verify upon later.
