### ISSUE TITLE
Wrong parameter in dump_jwk used

### ISSUE THREAD

**Issue by gheift** [fffonion/lua-resty-openssl#130]
In https://github.com/fffonion/lua-resty-openssl/blob/89195843cfbfac9dcbf071832aa9303a347871b4/lib/resty/openssl/auxiliary/jwk.lua#L234 the wrong parameter is used. The line should be

`y = b64.encode_base64url(params.y:to_binary()), `

**Comment by fffonion** [comment]
Thank you @gheift !
