### ISSUE TITLE
Documentation for pkey:verify inconsistent

### ISSUE THREAD

**Issue by epikur-io** [fffonion/lua-resty-openssl#145]
Hi,

I stumbled upon the [pkey:verify](https://github.com/fffonion/lua-resty-openssl/blob/master/lib/resty/openssl/pkey.lua#L841) method.
The [documentation](https://github.com/fffonion/lua-resty-openssl#pkeyverify) states that in case of a verification failure of the signature, it will return false and no error. The documentation and the code are inconsistent because an error is also returned for invalid signatures.

I think either the documentation or code needs to be updated.

Kind regards,
Manuel

---

<sup>Manuel Gugel <manuel_sebastian.gugel@[mercedes-benz.com](http://mercedes-benz.com/)>, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

<sup>Gregor Gebhardt <gregor.gebhardt@[mercedes-benz.com](http://mercedes-benz.com/)>, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

**Comment by fffonion** [comment]
@epikur-io Thanks for the input. IIRC from OpenSSL 3.x it starts to emit errors on verify failure; while OpenSSL 1.1.x gives empty error and it
was when the document was written. I will update the document clarify it. : )
