### ISSUE TITLE
OpenSSL Version Compatibility Question

### ISSUE THREAD

**Issue by frankgreco** [fffonion/lua-resty-openssl#149]
Is there a way to get `mac.lua` to work without OpenSSL v3? That file depends on `EVP_MAC_CTX` which seems to only exist in v3.

**Comment by fffonion** [comment]
@frankgreco no that will only be available in openssl 3.x. For lower versions, you can use resty.openssl.hmac (which by the name only implements HMAC).

**Comment by frankgreco** [comment]
@fffonion Thanks for the quick reply. Am I correct in assuming that usage of `mac.lua` requires manual installations of OpenResty given that the release assets have v1?

**Comment by fffonion** [comment]
@frankgreco correct, you will need to compile openresty against openssl 3.x before they release openssl 3.x artifacts.

**Comment by fffonion** [comment]
Do note that `resty.openssl.mac` is basically a wrap up for HMAC and CMAC. If you are just using HMAC there's no real requirement to move to that considering you are not on openssl 3.x after all.

**Comment by frankgreco** [comment]
Thanks! And understood. This repo is a transitive dep for something I need unfortunately.
