### ISSUE TITLE
Iterating over x509.altname stack crashes when encountering type IP

### ISSUE THREAD

**Issue by Evengard** [fffonion/lua-resty-openssl#18]
From time to time I am getting a certificate which have the altname IP-type fields present. I don't really need them, but I still need to iterate over all altnames to retrieve the needed ones, but iteration crashes when encountering the IP type.
Replacing the `error("NYI")` by `v = "NOTIMPLEMENTED"` helped, but that's more of a hack than a solution.
I wonder if it is possible to somehow patch it that it doesn't crash on nonimplemented/unknown altname types.

**Comment by fffonion** [comment]
@Evengard It's actually just fixed : ) Please try the 0.7.1 release.

**Comment by Evengard** [comment]
Oh ok thanks, gonna retry =)
