### ISSUE TITLE
HMAC crash

### ISSUE THREAD

**Issue by altrifon-te** [fffonion/lua-resty-openssl#184]
There is some an unexpected behavior of this code:

`local hmac  = assert(require("resty.openssl.hmac"))`
`hmac.new("Secret", "sha256")`
`hmac:update("Key")`
`assert(hmac:final())`

The logs show:

2024/09/16 16:22:13 [alert] 277310#0: worker process 277320 exited on signal 11 (core dumped)

dmesg:

openresty[278240]: segfault at 0 ip 000077ca1da18bc4 sp 00007fffca8edee8 error 4 in libcrypto.so.3[77ca1d8b3000+333000] likely on CPU 6 (core 12, socket 0)

**Comment by fffonion** [comment]
```lua
local hmac  = assert(require("resty.openssl.hmac"))
local hmac_instance = hmac.new("Secret", "sha256")
hmac_instance:update("Key")
assert(hmac_instance:final())
```
would work
