### ISSUE TITLE
can't find the module x509

### ISSUE THREAD

**Issue by OnlyPiglet** [fffonion/lua-resty-openssl#2]
When I try to use require("openssl")
the program cause a error like this
resty/openssl/pkey.lua:15: module 'resty.openssl.include.x509' not found:
	no field package.preload['resty.openssl.include.x509']

and I didn't find the x509.lua in the directory of include.

**Comment by fffonion** [comment]
@OnlyPiglet there might be some packaging error, which tool (luarocks or opm) are you installing this library with and which version of this library are you using?

**Comment by fffonion** [comment]
closing for inactive state, please reopen if problem still exists : )

**Comment by liuyangcode** [comment]
同样的问题

**Comment by fffonion** [comment]
@liuyangcode Please use English in github issues. Which version are you using and do you install it via luarocks or opm?
