### ISSUE TITLE
Read custom X509 extension

### ISSUE THREAD

**Issue by lgtti** [fffonion/lua-resty-openssl#27]
Hi, how can i read the value of a custom x509 certificate extension?
I have a user certificate that contains the '1.2.840.10070.8.1' OID (https://oidref.com/1.2.840.10070). This OID contains the value for the user RBAC role that i need to manage in nginx.

Using the get_extension method, passing the '1.2.840.10070.8.1' value, the result value is nil.

**Comment by fffonion** [comment]
Hi @lgtti , you might need to create the NID object as the OID might not defined by openssl. Please use https://github.com/fffonion/lua-resty-openssl/blob/master/examples/tls-alpn-01.lua#L10 as an example on how to create custom NID from any OID.

**Comment by lgtti** [comment]
Thank you very much for the hint (i have noticed that in the documentation there is a link for this problem but yesterday i haven't seen it, sorry).

But, i have a new problem.
With the code:
`local nid = objects.create(
            "1.2.840.10070.8.1", -- nid
            "id-IEC62351-IECuserRoles",  -- sn
            "id-IEC62351-IECuserRoles"     -- ln
          )
          
          local rbacRole, pos, err = client_cert:get_extension('1.2.840.10070.8.1')
          if not err then
            ngx.header['X-rbacrole'] = rbacRole:text()
            ngx.header['X-rbacrole-pos'] = tostring(pos)
          else
            ngx.header['X-rbacrole'] = 'ext not found'
          end`

I got an header with the position value ( x-rbacrole-pos: 6 that is correct) but not the text representation (the header is missing, so the value is empty).
This means that the corresponding extension value is empty?

Using the 'openssl x509 -in insttestkube.pem -text' command i found the extension and its value:

1.2.840.10070.8.1:
                0.0.0......raTsint...


Where is the problem?

**Comment by fffonion** [comment]
@lgtti Try to do a base64 encode of the value, the header might be missing because it contains weird characters. If that still doesn't work, would you be able to share a sample cert so I can test against?

**Comment by lgtti** [comment]
The problem persists.

Here you can find a sample certificate which contains the extension.

-----BEGIN CERTIFICATE-----
MIIDdjCCAl6gAwIBAgIUNBDee3+Zlq0gh3P1V6OPXfPZimMwDQYJKoZIhvcNAQEL
BQAwaTETMBEGA1UEAwwKSm9obiBTbWl0aDEsMCoGCSqGSIb3DQEJARYdam9obi5z
bWl0aEBxdW92YWRpc2dsb2JhbC5jb20xFzAVBgNVBAoMDlF1b1ZhZGlzIEdyb3Vw
MQswCQYDVQQGEwJVUzAeFw0yMTA3MjAxMjM4MDNaFw0yMjA3MjAxMjM4MDNaMGkx
EzARBgNVBAMMCkpvaG4gU21pdGgxLDAqBgkqhkiG9w0BCQEWHWpvaG4uc21pdGhA
cXVvdmFkaXNnbG9iYWwuY29tMRcwFQYDVQQKDA5RdW9WYWRpcyBHcm91cDELMAkG
A1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCw9lH8Ymhd
TnS+rg4aXbPIa2TYB2xiUyfIqNm6z5gc3vaIz+NgtjKm8yQ5zNcaUuNfa7XrpwQ+
YTxi7z9mmwSId2E5/F4ZFe9B5Qk3/g0VOEIzDbE5BeDPxGuHvi8CzKnwMSVS73x3
1aMHrd8XPQpx/NpJhhmqVj9B/MQI2Z3SKs93D5MmEqPvkMsE0gbHiGwVNIIJnlwz
+290tTKo+RsA4o0YvtmvuqqiRUqJm/C+OCeQJ4fKpHyVqegM2yBcaYmamdrSoYIF
9jqHuMRg2g6QWP3ze1Maop8fqYUxmhKloFmzXxV65cMYrYQ7YaRbqTr4/0qh0eY2
FQPoL+e/WA7BAgMBAAGjFjAUMBIGByqGSM5WCAEEBwwFcHJvdmEwDQYJKoZIhvcN
AQELBQADggEBAJPxqrJ1wvj42WhgG37WaUG6P9+qs/fHdg3193kp7skAuXN7g80y
TJCWW7lpa+fYvBqwOM1YgDv/V3r/96scEtocjuO47tyvIQ0EdDvgdxFiscGmh7JH
FiqQ5UiQ5KdQsaoiRV98m0HNyRRDIs0D1fB4zWnGEuIyhCYVGMusHTg2UmmDVVth
HjzyiDsQuf+sccXXyYDfEhAbG70FaAOsEOd2xXXQOC4IUbRaad7ID7AeH+sNfeXO
R2Dd/Wb62fQ8ZVV/T9/+GY2IxohQmxMMDxRvmLAP2LGBlKedIYdmy/qR5GSgsBgu
liYfIZSmpBzrhGygyQB50lURtovsBvHplDI=
-----END CERTIFICATE-----

Using the command 'openssl x509 -in test.crt -text' you can see the extension contained in the certificate.

My code is here:
`local openssl_x509 = require "resty.openssl.x509"
          local objects = require "resty.openssl.objects" 
          local client_cert, err = openssl_x509.new(testpemcrt)

          if not err then
            ngx.header['X-client_cert'] = 'found'
          else
            ngx.header['X-client_cert'] = tostring(err)
          end

          ngx.header['X-client_cert_subject_name'] = tostring(client_cert:get_subject_name())

          local nid = objects.create(
            "1.2.840.10070.8.1", -- nid
            "id-IEC62351-IECuserRoles",  -- sn
            "id IEC62351 IECuserRoles"     -- ln
          )

          local encode_base64 = ngx.encode_base64
          
          local rbacRole, pos, err = client_cert:get_extension('1.2.840.10070.8.1')
          if not err then
            local roleVal = encode_base64(rbacRole:text(), true)
            ngx.header['X-rbacrole-val'] = roleVal
            ngx.header['X-rbacrole-pos'] = tostring(pos)
          else
            ngx.header['X-rbacrole'] = 'is nil'
          end`

**Comment by fffonion** [comment]
@lgtti I see, I think this is expected, as we are using `X509V3_EXT_print` here and it won't work with unknown extensions,
in fact, the x509 applet fallback to use `ASN1_STRING_print` while `X509V3_EXT_print` failed. I can add the same
behaviour here in `extension:text()`.

**Comment by lgtti** [comment]
Can you share me an example of the usage of to_der?
How can i retrive the extension using this format?

I cannot wait for the fix because i'm using Kong Enterprise and i don't think that a new version of lua-resty-openssl can be ported in the mainstream easily.

**Comment by fffonion** [comment]
I didn't read the specification in detail, but based on the output I can go through the basic idea here:
```lua
local der = rbacRole:to_der()
-- der = '\x0C\x05\x70\x72\x6F\x76\x61'
```
In ASN.1 encoding, 0x0C means UTF8String, then 0x05 is the length of it, the next 5 byte `\x70\x72\x6F\x76\x61`
is the value of the UTF8String, which print as `prova`. You can write your own decoder or use some existing asn1
lua decoder (https://github.com/Kong/kong/blob/911385466571e4f72999fa43419daafae08159d0/kong/plugins/ldap-auth/asn1.lua, but i don't have a doc for that library).

But I do strongly recommend to read the specification, or at least consult the creator of those certificates on how the
value are encoded. Since from google it seems the extension is a sequence not a utf8string, but maybe people
are storing them in a different encoding other than the standard.

```
id-IEC62351 OBJECT_IDENTIFIER::= { 1 2 840 10070 }
id-IECuserRoles OBJECT_IDENTIFIER::= id-IEC62351 { 8 1 }
IECUserRoles::= SEQUENCE OF UserRoleInfo

UserRoleInfo::= SEQUENCE { -- contains the role information blob
-- IEC62351 specific parameter
userRole SEQUENCE SIZE (1..MAX) OF RoleID
aor UTF8String (SIZE(1..64)),
revision INTEGER (0..255),
roleDefinition UTF8String (0..23) OPTIONAL,
-- optional fields to be used within IEEE 1815 and IEC60870-5
operation Operation OPTIONAL,
statusChangeSequenceNumber INTEGER (0..4294967295) OPTIONAL,
}
RoleId::= INTEGER (-32768..32767)
Operation::= ENUMERATED { Add (1), Delete (2), Change (3) }
```

**Comment by fffonion** [comment]
@lgtti Also since you mentioned you are using Kong Enterprise, would you also connect with support team
to sync up on the discussion here?

**Comment by lgtti** [comment]
Using the to_der function solve the problem.
The "prova" value stored in the example certificate is only a test value, normally the iec62351-8 specify a different (and more complex structure) as explained by your comment.

Now my problem is to perform a 2-complement operation on the value of the extension (tilde character is not good in the kong yaml declaration) :)

Talking of Enterprise Kong support, i'm very happy to sync their support team for the problem. I'm moving for that in the next weeks.

Thank you very much for your support!

**Comment by lgtti** [comment]
Hi, if you release a version 0.7.4 with this bugfix we can open a support ticket to Kong Enterprise to update the library before the new version (https://docs.konghq.com/enterprise/changelog/) that is in beta and includes your library version 0.7.3.

**Comment by fffonion** [comment]
@lgtti Sounds good, I will create a release.

**Comment by fffonion** [comment]
Closing this as the new version has been released. Feel free to reopen if you still have questions : )
