### ISSUE TITLE
Makefile doesn't installs all files

### ISSUE THREAD

**Issue by olfway** [fffonion/lua-resty-openssl#33]
It has
```
$(INSTALL) lib/resty/openssl*.lua $(DESTDIR)$(LUA_LIB_DIR)/resty/
$(INSTALL) lib/resty/openssl/*.lua $(DESTDIR)$(LUA_LIB_DIR)/resty/openssl/
```
but this misses "auxiliary", "include" and "x509" subdirs in resty/openssl/ dir

I guess the same problem was in #2

**Comment by fffonion** [comment]
@olfway Oops, will fix that, thanks! In the meanwhile I would recommand to install using package manager like luarocks or opm.
