### ISSUE TITLE
Dependency to git for installation of version 0.8.2-1

### ISSUE THREAD

**Issue by mbreevoort** [fffonion/lua-resty-openssl#44]
When I install version 0.8.2-1 I get an error 
`luarocks install lua-resty-openssl 0.8.2-1`
Error
```
Error: 'git' program not found. Make sure Git is installed and is available in your PATH (or you may want to edit the 'variables.GIT' value in file '/usr/local/openresty/luajit/etc/luarocks/config-5.1.lua')
```
After installing git the installation succeeded.

When I install the previous version I do not need to install git in my docker container.

When I check https://luarocks.org/modules/fffonion/lua-resty-openssl/0.8.2-1 there is no src download, with 0.8.1-1 there is. Is it  on purpose there is no src download on the newer version?

Would be nice there is no dependency on git to install the module, is it possible the src download is available on module install?

**Comment by fffonion** [comment]
@mbreevoort Seems to be an error when publishing, I republished 0.8.2-1 including a src archive.

**Comment by mbreevoort** [comment]
thnx fixed, git is not necessary anymore.
