### ISSUE TITLE
Hot to get fingerprint?

### ISSUE THREAD

**Issue by snpcp** [fffonion/lua-resty-openssl#89]
hello,

Hot to get fingerprint by lua-resty-openssl?

thanks.

**Comment by fffonion** [comment]
@snpcp could you provide more context? What fingerprint do you want to get?

**Comment by snpcp** [comment]
likeness: [Nginx](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) $ssl_client_fingerprint
or
openssl x509 -noout -fingerprint -sha1 -inform pem -in xxx.cer

**Comment by snpcp** [comment]
I found a impl in [lua-resty-jwt](https://github.com/SkyLothar/lua-resty-jwt/blob/master/lib/resty/evp.lua#L300), but that will import new module to my project.

**Comment by fffonion** [comment]
you will then need `x509:digest` https://github.com/fffonion/lua-resty-openssl#x509digest

**Comment by snpcp** [comment]
Thanks you, It's working.
