### ISSUE TITLE
尝试解密微信支付AEAD_AES_256_GCM的加密文本遇到错误:cipher:final: EVP_CipherFinal_ex failed

### ISSUE THREAD

**Issue by xiangnanscu** [fffonion/lua-resty-openssl#95]
你好大神, 我尝试解码微信支付(https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_5.shtml) 传过来的加密文本(AEAD_AES_256_GCM), 出错, 提示`cipher:final: EVP_CipherFinal_ex failed`. 

于是我尝试使用贵库的aes-256-gcm来加密同一段文本, 发现绝大多部分字符和微信支付相同, 只有结尾几个字符不一样(微信以`TxPo11gThp6ldZaomAaeB1`结尾, 贵库以`Q=`结尾):
## 微信密件:
Fv0Lo+9D/umAGsuf0me2hfeKKSYzCwRga2ZNyap+ITSVB1lkiRYfaxQIxcQ+DFzsmhcBfP7lqmyK+ldu17vdXoh2ctIcdXO7skKFnLVQhTbE/pPqoAt/npXqa4YGAmUZXFDw1i/OM5muoKE3uOK54JqahsovwP7ixkb09gkoUnpOFQVu57glYn79XwoE3iVGLIojdszqCVaSS3a7EbIDKmSEvWsT0HB4eC2t5J6NhFyn/MCC5d1tcmmqcoa3hIdL4qDS2v4PiOis3x11dkDbcBYCRxwo4t+H78QgVUl/40ZcLAwYNF9rdfyFSt9lWedSHCPt0ulGebvrXLg+7CqMqL4QD4c/t007beHZgR5paMY6HOhOcHv/njETITx5m1tRUNOeatxNmdq5Q3J0BeB9GDcV5mGlgcx2njEfjnoWn3aPRfeTIYYzLT7BZP2hifhkJlF2qSTx3/So55qVtFLzt8DhBSKyzUrR40/Eb/pgmduiFxo/HfTvgDu9Cumphy1aB4UqvUks9+fK7JOiLN7To2rkXJsJFfqPCOrSN/u0ZFYgIFylOmTxPo11gThp6ldZaomAaeB1

## lua-resty-openssl密件
Fv0Lo+9D/umAGsuf0me2hfeKKSYzCwRga2ZNyap+ITSVB1lkiRYfaxQIxcQ+DFzsmhcBfP7lqmyK+ldu17vdXoh2ctIcdXO7skKFnLVQhTbE/pPqoAt/npXqa4YGAmUZXFDw1i/OM5muoKE3uOK54JqahsovwP7ixkb09gkoUnpOFQVu57glYn79XwoE3iVGLIojdszqCVaSS3a7EbIDKmSEvWsT0HB4eC2t5J6NhFyn/MCC5d1tcmmqcoa3hIdL4qDS2v4PiOis3x11dkDbcBYCRxwo4t+H78QgVUl/40ZcLAwYNF9rdfyFSt9lWedSHCPt0ulGebvrXLg+7CqMqL4QD4c/t007beHZgR5paMY6HOhOcHv/njETITx5m1tRUNOeatxNmdq5Q3J0BeB9GDcV5mGlgcx2njEfjnoWn3aPRfeTIYYzLT7BZP2hifhkJlF2qSTx3/So55qVtFLzt8DhBSKyzUrR40/Eb/pgmduiFxo/HfTvgDu9Cumphy1aB4UqvUks9+fK7JOiLN7To2rkXJsJFfqPCOrSN/u0ZFYgIFylOmQ=

 这是代码:
```lua
local key = string.rep("0", 32)
local iv = "gLm1Ft8R0tva"
local aad = "transaction"
local mode = "aes-256-gcm"

local to_be_encrypted = '{"mchid":"**","appid":"**","out_trade_no":"**","transaction_id":"**","trade_type":"JSAPI","trade_state":"SUCCESS","trade_state_desc":"支付成功","bank_type":"UPQUICKPASS_DEBIT","attach":"","success_time":"2023-01-28T14:25:02+08:00","payer":{"openid":"**"},"amount":{"total":10,"payer_total":10,"currency":"CNY","payer_currency":"CNY"}}'
local wx_encrypt = "Fv0Lo+9D/umAGsuf0me2hfeKKSYzCwRga2ZNyap+ITSVB1lkiRYfaxQIxcQ+DFzsmhcBfP7lqmyK+ldu17vdXoh2ctIcdXO7skKFnLVQhTbE/pPqoAt/npXqa4YGAmUZXFDw1i/OM5muoKE3uOK54JqahsovwP7ixkb09gkoUnpOFQVu57glYn79XwoE3iVGLIojdszqCVaSS3a7EbIDKmSEvWsT0HB4eC2t5J6NhFyn/MCC5d1tcmmqcoa3hIdL4qDS2v4PiOis3x11dkDbcBYCRxwo4t+H78QgVUl/40ZcLAwYNF9rdfyFSt9lWedSHCPt0ulGebvrXLg+7CqMqL4QD4c/t007beHZgR5paMY6HOhOcHv/njETITx5m1tRUNOeatxNmdq5Q3J0BeB9GDcV5mGlgcx2njEfjnoWn3aPRfeTIYYzLT7BZP2hifhkJlF2qSTx3/So55qVtFLzt8DhBSKyzUrR40/Eb/pgmduiFxo/HfTvgDu9Cumphy1aB4UqvUks9+fK7JOiLN7To2rkXJsJFfqPCOrSN/u0ZFYgIFylOmTxPo11gThp6ldZaomAaeB1"

local cipher = assert(require("resty.openssl.cipher").new(mode))
local encrypted = assert(cipher:encrypt(key, iv, to_be_encrypted, true, aad))

ngx.say("加密文本是否和微信支付一致: ", ngx.encode_base64(encrypted) == wx_encrypt)

local tag = assert(cipher:get_aead_tag())

-- ngx.say("tag is: ", ngx.encode_base64(tag), " ", #tag)

-- 解密自己加密的文本没有问题
local decrypted = assert(cipher:decrypt(key, iv, encrypted, true, aad, tag))
print(decrypted)
```

**Comment by fffonion** [comment]
你好，部分加密库的实现把AEAD的tag放到了加密结果的末尾，需要自己切割。可以参考https://github.com/fffonion/lua-resty-openssl/blob/master/examples/aes-gcm-aead.lua#L62

**Comment by xiangnanscu** [comment]
感谢!
